### ISSUE TITLE
[FEATURE REQUEST] Set Dynamic As Default

### ISSUE THREAD

**Issue by NotDarkn** [whoeevee/EeveeSpotify#143]
Hi!

I recently installed EeveeSpotify v4.0 (about ~1 hour ago) and when I went to open the app, it auto-defaulted to having no premium subscription right away. I thought v4.0 broke something from v3.1, but no. Instead, the default option was Static rather than Dynamic and switching over to Dynamic fixed it.

To summarize: Can EeveeSpotify default to Dynamic and fallback to Static as the patching method? Would be convenient and nice to see.

**Comment by whoeevee** [comment]
It’s probably not an issue with the static method, but rather due to updating from an older version. After updating, you need to set the Premium patching method in the EeveeSpotify settings (either static or dynamic) because it’s not set by default, and the tweak does nothing (EeveeSpotify sets the method on fetching bootstrap, which doesn’t occur if you are already logged in). I’ve added this notice in the release description.

**Comment by NotDarkn** [comment]
> It’s probably not an issue with the static method, but rather due to updating from an older version. After updating, you need to set the Premium patching method in the EeveeSpotify settings (either static or dynamic) because it’s not set by default, and the tweak does nothing (EeveeSpotify sets the method on fetching bootstrap, which doesn’t occur if you are already logged in). I’ve added this notice in the release description.

ah alright i see, thanks for the clarification :D
