### ISSUE TITLE
[Feature Request] Live Lyrics (similar to how Apple Music does it) 

### ISSUE THREAD

**Issue by Cosmic1212** [whoeevee/EeveeSpotify#203]
![image](https://github.com/whoeevee/EeveeSpotify/assets/171290658/6d439321-431a-42da-b35b-3a202e3b3eff)

this from spicetify - beautiful Lyrics

https://github.com/surfbryce/beautiful-lyrics/

**Comment by yodaluca23** [comment]
Syllable timed lyrics is not directly supported by Spotify so they would probably instead of just injecting lyrics into the already existing lyric card, they would probably have to make a custom one... This would probably be very difficult to implement, also, I'm not sure if free Musixmatch accounts have access to syllable times lyrics.
