### ISSUE TITLE
[Bug] genius fallback does not occur when musixmatch lyrics are restricted

### ISSUE THREAD

**Issue by saccharinesky** [whoeevee/EeveeSpotify#215]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

A significant amount of songs from an artist I listen to have their lyrics restricted on musixmatch. I feel like that genius fallback should occur in those situations, as it does not seem to occur as is.

**Comment by saccharinesky** [comment]
upon further inspection it seems the fallback works correctly with some songs and doesn't with others, i suppose this is more a genius search issue

**Comment by whoeevee** [comment]
it's fixed in 4.3
genius fallback always occurs when lyrics are restricted on Musixmatch
if you see the "Couldn't load the lyrics for this song" message, the tweak was unable to find the lyrics on Genius, and it’s likely not an issue

you can switch the lyrics source to Genius and see if it works
you can also send console messages and song examples
