### ISSUE TITLE
[Improvement] Musixmatch translation

### ISSUE THREAD

**Issue by NON1919** [whoeevee/EeveeSpotify#238]
Can you add a button to click and it will be like this?

![z5624079493919_91b981434c5ba7ad8f3c9e4cce8b89fa](https://github.com/whoeevee/EeveeSpotify/assets/90590902/e347dcda-344b-4c1e-a545-4a920e6a599b)

Or just create a button to show translated lyrics not replace the original lyrics

![image](https://github.com/whoeevee/EeveeSpotify/assets/90590902/b556bb20-8767-4a1e-9f91-fa63d6d36199)

**Comment by yodaluca23** [comment]
Looks like this was an experimental feature from about two years ago if the code is still in the app, that would be great because then it could be hooked and edited instead of making new...

**Comment by NON1919** [comment]
> Looks like this was an experimental feature from about two years ago if the code is still in the app, that would be great because then it could be hooked and edited instead of making new...

it’s still in the app because this is premium feature

**Comment by asdfzxcvbn** [comment]
if you can provide an account with the translation button then we can implement this

**Comment by NON1919** [comment]
> if you can provide an account with the translation button then we can implement this

okay i will find it

**Comment by NON1919** [comment]
> if you can provide an account with the translation button then we can implement this

hi i found it so how can i send you the account?
can you send me the telegram username

**Comment by NON1919** [comment]
@yodaluca23 
@asdfzxcvbn 
@whoeevee

**Comment by asdfzxcvbn** [comment]
> > if you can provide an account with the translation button then we can implement this
> 
> 
> 
> hi i found it so how can i send you the account?
> 
> can you send me the telegram username

dm me @asdfzxcvbn0

**Comment by whoeevee** [comment]
implemented with 98f6f9e
check out https://github.com/whoeevee/EeveeSpotify/actions/runs/9918263789

**Comment by NON1919** [comment]
> implemented with [98f6f9e](https://github.com/whoeevee/EeveeSpotify/commit/98f6f9e5a2cbd719f54b63e027fcac1c0ad51ab6)
> check out https://github.com/whoeevee/EeveeSpotify/actions/runs/9918263789

i tested it
it works fine

**Comment by NON1919** [comment]
> implemented with [98f6f9e](https://github.com/whoeevee/EeveeSpotify/commit/98f6f9e5a2cbd719f54b63e027fcac1c0ad51ab6)
> check out https://github.com/whoeevee/EeveeSpotify/actions/runs/9918263789

![IMG_0279](https://github.com/user-attachments/assets/cb850eb1-72c0-4ffd-97c3-4367902ffd4a)
![IMG_0280](https://github.com/user-attachments/assets/30eea7be-9536-47a0-9d8f-4b334c13e962)
![IMG_0281](https://github.com/user-attachments/assets/c447f3ae-ae33-4188-80e6-9a1720da5fb8)

**Comment by NON1919** [comment]
since it done, i will close this

**Comment by yodaluca23** [comment]
@whoeevee This works great! I am wondering could we have a toggle to bring back the old implementation. Because some people may want to only see the translated lyrics. Also, the new implementation doesn't let you view the translations in the card view. Also, it doesn't work for Romanized lyrics, it just does the old implementation, with Musixmatch and Genius...

**Comment by yodaluca23** [comment]
> @whoeevee This works great! I am wondering could we have a toggle to bring back the old implementation. Because some people may want to only see the translated lyrics. Also, the new implementation doesn't let you view the translations in the card view. Also, it doesn't work for Romanized lyrics, it just does the old implementation, with Musixmatch and Genius...
> 
> Also, could you make it if Romanized lyrics and a translation language are on to first check Romanized if that doesn't exist then the translation language?

Also, if the song is already in the translation language, it translates to some other language? can you make the button just not show up?

**Comment by yodaluca23** [comment]
> Also, if the song is already in the translation language, it translates to some other language? can you make the button just not show up?

It seems to be just that one song, must be weird Musixmatch thing, probably...
But still could be fixed maybe?
Affected Songs:
https://open.spotify.com/track/37f4ITSlgPX81ad2EvmVQr
https://open.spotify.com/track/3MEYFivt6bilQ9q9mFWZ4g

It seems that its getting the translation from description... not subtitle matched or lyric matched.... and the description is not the correct translation... 

But it gives an actual translation from the API, instead of blank response, with language key being ```tr``` for Alone, and ```lv``` for Fight Song...

selected_language is the set ```en``` as expected so maybe have a check before accepting it as lyrics, to make sure the language key matches the users selected one? Before actually using the translation...

**Comment by whoeevee** [comment]
There won’t be toggles to bring back the old implementation or search for romanized lyrics at first.

The translation issues with some songs are only related to the Musixmatch API. It provides the translation, marks it as an English translation, etc. I will probably implement a feature to avoid using the translation if it’s the original song language.
