### ISSUE TITLE
[Bug] Musixmatch source doesn’t work with local files

### ISSUE THREAD

**Issue by diow142** [whoeevee/EeveeSpotify#338]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Local files do not have lyrics if using musixmatch, however if using lrclib the local files will have lyrics. I know that musixmatch does have lyrics for these songs as I use lyrics-plus on desktop.

**Comment by yodaluca23** [comment]
Probably because LRCLIB uses the song name and artist to do a search but MusixMatch uses the Spotify ID if you're listening to local music obviously it won't have a Spotify ID... could probably add a check for if the song is local or not and if so, then do a search using song and artist name on musixmatch, instead of Spotify ID...

**Comment by ElliotCHEN37** [comment]
https://developer.musixmatch.com/documentation/api-reference/track-get
Musixmatch uses a track id

**Comment by ElliotCHEN37** [comment]
though, you still can get lyrics without track id (using artist and title)
https://github.com/fashni/MxLRC

**Comment by whoeevee** [comment]
it should work in v4.9

**Comment by diow142** [comment]
Can confirm it does work
