### ISSUE TITLE
[Bug] Lrclib has synced lyrics but eeveespotify is not using it and also eeveespotify is using the wrong lyrics

### ISSUE THREAD

**Issue by Diowboss** [whoeevee/EeveeSpotify#411]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![IMG_0810](https://github.com/user-attachments/assets/e4a358ed-8e9f-4d25-93ec-73e792adea0c)
(what eeveespotify is showing)
![Screenshot 2024-09-29 at 01-53-50 LRCLIB](https://github.com/user-attachments/assets/38e0efc5-c609-4f7b-a75b-2cebeff38caf)
(what lrclib has)

![IMG_0811](https://github.com/user-attachments/assets/0d519da9-bdd2-4414-b889-7e47133cbcc8)
(eevee spotify using wrong lyrics)
![Screenshot 2024-09-29 at 01-54-45 LRCLIB](https://github.com/user-attachments/assets/2869fa03-366c-412a-8b49-b65d82927989)
(the actual lyrics)
![Screenshot 2024-09-29 at 01-56-35 LRCLIB](https://github.com/user-attachments/assets/322cc718-ba2e-475a-8641-f80de12b8de6)
(the wrong song its pulling the lyrics from)
![Screenshot 2024-09-29 at 01-56-33 LRCLIB](https://github.com/user-attachments/assets/1947e0ac-f055-4f37-8f7b-0be0fcee17a5)
(song its supposed to be pulling the lyrics from)

My best guess is that the lrclib api has changed.

**Comment by Diowboss** [comment]
the reason might be that eeveespotify is not using the "album_name" parameter to look up lyrics

**Comment by whoeevee** [comment]
The LRCLIB API hasn't changed, but you may sometimes see wrong lyrics due to how the tweak searches for songs. EeveeSpotify searches for songs by their name and primary artist, generally picking the first matching result. In one case, there were two identical songs on LRCLIB, and the first one didn’t have synced lyrics, which seems to be resolved now. In another case, there are tracks with the same title and even part of the same artist name, "wonder", but a different one is more popular and selected first. I believe that's rare anyway and only affects a few songs.

**Comment by Diowboss** [comment]
for the spicetify plugin “lyrics plus” it doesn’t have the second issue
