### ISSUE TITLE
Lyrics becoming server sided.

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#42]
So I noticed this 5dbc86c commit, is there any other info on this? Could we make it replace the Spotify-provided lyrics with it directly fetching from Musixmatch API (more likely with some other alternative bc free API [even if each user used their own API key] sucks)? Why is Spotify doing this?

**Comment by asdfzxcvbn** [comment]
after checking the HTTP response received for lyrics, it seems to be protobuf data with some weird extra characters. it *might* be possible, but it would likely be a challenge.

EeveeSpotify is only a tweak to give you free premium. no workarounds for server-sided features will be implemented in this tweak (which is why all feature requests are being closed)

maybe someone else can pick this up and implement it in a seperate tweak if they'd like.

**Comment by whoeevee** [comment]
wait how did I reopen this
