### ISSUE TITLE
[Feature Req] Option to Remove the new Create + button

### ISSUE THREAD

**Issue by gototheskinny** [whoeevee/EeveeSpotify#470]
If it's possible that would be great, Thank you.

<details>
  <summary>Screenshot</summary>
  
 ![image](https://github.com/user-attachments/assets/8012d763-caa4-4ba2-9a59-f13a51e57346)
  
</details>

**Comment by asdfzxcvbn** [comment]
does it go away if you turn on overwrite configuration?

**Comment by gototheskinny** [comment]
> does it go away if you turn on overwrite configuration?

Yes it did go away. Is that the permanent solution for this?

**Comment by ElliotCHEN37** [comment]
> > does it go away if you turn on overwrite configuration?
> 
> Yes it did go away. Is that the permanent solution for this? 

Perhaps, cuz this config file defines many UI/UX

**Comment by whoeevee** [comment]
zx apparently seems too lazy to reply properly

If I understand correctly, this button is used to quickly create albums. It's not new and is defined in the remote configuration, which is account-specific. Only Spotify determines whether to display it for your account or not. Many people, including myself, don’t see this button, and when you enable Overwrite Configuration, it disappears because the entire configuration is replaced, including UX parameters, with one that doesn’t contain the button.

To remove it, we would either need to modify the parameter affecting this button in the configuration, or, even worse, hook into UITabBar-related classes to hide it. Personally, I don’t see the point in removing it. It’s not like the Premium button, which was just there to annoy you. This button actually has a function — creating albums. It’s similar to requests to hide podcasts, which weren’t fulfilled. If you don’t like podcasts, don’t look at them or visit the tab with them. If you don’t like this button, just don’t use it. I don’t like the idea of turning EeveeSpotify into a settings hub with options like “Hide Create Button,” “Hide Podcasts,” etc.

Maybe one day a settings section where you can control configuration parameters will be implemented, but it’s going to be quite challenging to make it robust, given that the parameters have different value types, may not always be present, and so on. Currently, there are no plans for this.

Yes, you can use the Overwrite Configuration feature. We only update the configuration when it causes issues, like recent crashes (when clicking on the three dots on a song page). You should be able to use it for a long time, even if it gets updated. There probably won’t be this button unless Spotify decides to add it for Premium accounts that the configuration is dumped from.

**Comment by gototheskinny** [comment]
> zx apparently seems too lazy to reply properly
> 
> 
> 
> If I understand correctly, this button is used to quickly create albums. It's not new and is defined in the remote configuration, which is account-specific. Only Spotify determines whether to display it for your account or not. Many people, including myself, don’t see this button, and when you enable Overwrite Configuration, it disappears because the entire configuration is replaced, including UX parameters, with one that doesn’t contain the button.
> 
> 
> 
> To remove it, we would either need to modify the parameter affecting this button in the configuration, or, even worse, hook into UITabBar-related classes to hide it. Personally, I don’t see the point in removing it. It’s not like the Premium button, which was just there to annoy you. This button actually has a function — creating albums. It’s similar to requests to hide podcasts, which weren’t fulfilled. If you don’t like podcasts, don’t look at them or visit the tab with them. If you don’t like this button, just don’t use it. I don’t like the idea of turning EeveeSpotify into a settings hub with options like “Hide Create Button,” “Hide Podcasts,” etc.
> 
> 
> 
> Maybe one day a settings section where you can control configuration parameters will be implemented, but it’s going to be quite challenging to make it robust, given that the parameters have different value types, may not always be present, and so on. Currently, there are no plans for this.
> 
> 
> 
> Yes, you can use the Overwrite Configuration feature. We only update the configuration when it causes issues, like recent crashes (when clicking on the three dots on a song page). You should be able to use it for a long time, even if it gets updated. There probably won’t be this button unless Spotify decides to add it for Premium accounts that the configuration is dumped from.

I completely understand your reasoning, and I hope that in the future, these customizations will be implemented or a separate tweak like Sposify (an old Spotify customization tweak with a lot of options) will be created. For now, I’m totally fine with using the override option and not even using it at all (muscle memory makes me do it honestly).

Thank you so much for creating and improving this tweak. you’ve made Spotify so much better and bearable for many of us!
