### ISSUE TITLE
No such module 'SwiftProtobuf'

### ISSUE THREAD

**Issue by FeddyLix17** [whoeevee/EeveeSpotify#519]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I really hope this is not out of scope (compared to other issues).

As a native Italian speaker, I wanted to contribute to the existing translations by "refining them if necessary".

However, when I try to build the project locally from xcode to my physical iphone, I get the error 
`No such module 'SwiftProtobuf'`.

Despite installing it through brew, after hours of research I couldn't solve the issue by myself.

It is something easily fixable? (thanks in advance)

**Comment by yodaluca23** [comment]
Honestly, I just push to a dev branch on my fork, and build it using the actions to test it...

**Comment by FeddyLix17** [comment]
but in this way you don't just get the .deb packages?

**Comment by whoeevee** [comment]
hello, I appreciate your efforts. EeveeSpotify can be opened in Xcode; however, it needs to be built with theos (to get the .deb packages, install theos and execute `make package FINALPACKAGE=1`, for example)

SwiftProtobuf is a runtime library for using protbuf with swift. Since EeveeSpotify replaces lyrics and data, it depends on SwiftProtobuf. I’ve made it as a framework for theos integration, which is available here: https://github.com/whoeevee/swift-protobuf. you need to download it from the releases, unpack the .deb files, and place SwiftProtobuf.framework in the $THEOS/lib and $THEOS/lib/iphone/rootless (for rootless scheme)

for more details, you can look into the build action source code: https://github.com/whoeevee/EeveeSpotify/blob/swift/.github/workflows/build-swift.yml

**Comment by FeddyLix17** [comment]
Huge thanks! you just got me on the right track. 

Unfortunately, with the latest version of xcode I still couldn't compile the project anyway (the sdk was for ios18.1 instead of 18.0).

After downgrading to xcode 16.0, i was facing new kind of error during building the project (can't build the Orion module, Foundation.h file not found and the sysroot directory still pointing di ios18.1 SDK).

Guess for the moment i will only look at the italian localizable and make a PR if needed (and maybe learning more about swift development).

> btw i was able to build the .deb packages with the `make package FINALPACKAGE=1` command, thanks again!
