### ISSUE TITLE
W New Update can't wait for more changes!! Here are some bugs/fixes for the future

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#60]
- ![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/dc58b5f2-4fce-4d83-ab1f-fb63254d7d7f)
- Random lyrics for some songs or different language
- Spotify app doesn't show up in CarPlay 
- slightly buggy/randomly skipping songs,smart shuffle not working
-lyrics take a while to load/after songs starts or not even loading at all
-Jam feature, AI DJ, AI playlist not available or not working (idk if this is server sided or not, or if it possible to fix)
-premium button randomly comes back/having to constantly reload the app
- Tap on lyrics feature doesn't work, and the lyrics aren't time synced. Lyrics card color doesn't match the album art/theme and sometimes the text and the color are the same, so it unreadable.

**Comment by Jalapenook** [comment]
This tweak is awesome and I'm happy it's actively being updated with time I tend to stay away from the .0 updates though as they are most buggy 1.4.1 works flawlessly for me but I will continue to update with the double point updates 👍

**Comment by whoeevee** [comment]
thanks for the updates!

- The lyrics might be wrong for some songs. This is due to how the tweak searches songs on Genius. I've made it work in most cases. I'll probably fix different language lyrics by stripping whitespaces in the next release
- It should appear on CarPlay if you've installed it using TrollStore or a certificate with CarPlay entitlements
- Smart Shuffle actually works. Lyrics might take a while to load due to Genius (their API kinda slow)
- Spotify Jam, AI DJ, and AI Playlist are server-sided features, making it impossible to implement them in the tweak
- Weird. It's working fine for me. I suppose the premium button isn't a big problem anyway?
- Genius lyrics are not and will never be time-synced. I’ll look into unreadable colors in the next update
