### ISSUE TITLE
Swift vs Obj-C version?

### ISSUE THREAD

**Issue by bachig26** [whoeevee/EeveeSpotify#7]
Hi,
I just found your project and wanted to try it out.
But I found that there are two version being written: one in Swift and One in Obj-C.

I would like to know which one can I use or the one that will be maintained in future (I saw in one of the threads that its being rewritten in Obj-C)?
If you have few minutes to spare, please give me some brief info on these two and which one can I prefer to use more.

**Comment by asdfzxcvbn** [comment]
the swift version is the original version written by eevee, and the objc version is my rewrite.

if one updates, the other will update with the same changes.

the swift version relies on orion and substrate as external dependencies, and making an ipa could be painful if you don't know what you're doing. the objc version requires no external dependencies apart from its bundle (although i believe i could take out the need for that too)

while there are some _minor_ changes (pretty much just text), they are both _functionally_ the same. so you can use whichever you'd like, really, however one version may update before the other (no telling which one)

**Comment by samuelawachie** [comment]
Looks like you guys are prioritizing the Swift version over the Obj-C version. We've had a new release for the Swift hours ago, and nothing for the Obj-C. (sad face) :'(

**Comment by asdfzxcvbn** [comment]
> Looks like you guys are prioritizing the Swift version over the Obj-C version. We've had a new release for the Swift hours ago, and nothing for the Obj-C. (sad face) :'(

honestly everything works fine for me on objc v1.2 and i don't really see the need for me to maintain it anymore. i'm even considering just buying premium since i can afford it and it'll give me downloading

**Comment by samuelawachie** [comment]
> > Looks like you guys are prioritizing the Swift version over the Obj-C version. We've had a new release for the Swift hours ago, and nothing for the Obj-C. (sad face) :'(
> 
> honestly everything works fine for me on objc v1.2 and i don't really see the need for me to maintain it anymore. i'm even considering just buying premium since i can afford it and it'll give me downloading

That's a very personal message with a lot of I's and me's, etc. It pains me reading this and I realize that this is a volunteer project, but it's still disheartening that you're looking at this through a very individual view rather than a community view. That's okay of course, what with the capitalist thinking of every man for himself and as long as it works for me, I'm good.
I guess we shouldn't be expectant of much benevolence from freelance, OSS developers. For what it's worth, as I said before, something is better than anything. If only the settings issue I raised were resolved, then the app will be in a state that it can indeed be left alone for a while (or until it's patched out), but until then, I guess we just have to take what we're given. Thanks for all the work.

**Comment by whoeevee** [comment]
hey
the settings issue has been resolved in Swift 1.4

**Comment by samuelawachie** [comment]
> the settings issue has been resolved in Swift 1.4

Do you think this Swift version can be translated to ObjC and then released as that as well?

**Comment by asdfzxcvbn** [comment]
> > the settings issue has been resolved in Swift 1.4
> 
> Do you think this Swift version can be translated to ObjC and then released as that as well?

of course, but why?

**Comment by samuelawachie** [comment]
I installed the Swift version and it’s working well. I don’t know why it didn’t work that first time. 
Thanks guys
