### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#92]
I know this app works on iPhone but is It possible for it to work on MacBook, iPad, Apple Watch, or Apple TV? And is there alternative options like running it on android devices? Possibly a .apk file??

**Comment by yodaluca23** [comment]
For Android their is xManager and Revanced, MacOS, their SpotX and Block the Spot. This should already work on iPadOS. Apple Watch is impossible, because when you decrypt an iOS app, the watchOS app is not decrypted. You would need a watchOS jailbreak for that in which the most developed one only allowed for SSH access...

**Comment by fugegate** [comment]
> For Android their is xManager and Revanced, MacOS, their SpotX and Block the Spot. This should already work on iPadOS. Apple Watch is impossible, because when you decrypt an iOS app, the watchOS app is not decrypted. You would need a watchOS jailbreak for that in which the most developed one only allowed for SSH access...

Ok thanks!

**Comment by kopyl** [comment]
@yodaluca23 thank you.
I'm a developer myself which sell Software, but I haven't had a job for around a year, so I'm low on finances and your suggestion on SpotX came in handy for me right now.

Will get a subscription when I get a job.
